import { Html, Head, Main, NextScript } from "next/document";
// import { styles } from "../styles/home.module.css";
import { Box, useColorModeValue } from "@chakra-ui/react";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="https://media-exp1.licdn.com/dms/image/C4E03AQE0CYQmbbTiNw/profile-displayphoto-shrink_800_800/0/1660079360291?e=1675296000&v=beta&t=ZcOQGKSI-0qQMWplEXH4bXqxkwe5IGKEHPPtrUG7EiE"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Red+Hat+Text:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Box>
        <Main />
        <NextScript />
      </Box>
    </Html>
  );
}
