import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Flex, Box, Heading, Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <Box pt={20}>
      <Head>
        <title>Adrian Pantea Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="100vw" h={["100vh"]} px={[0, 0, 10, 40]}>
        <Box
          w="100%"
          display="flex"
          flexDir="column"
          justifyContent="space-evenly"
          alignItems="flex-end"
          px={[5, 5, 0]}
        >
          <Box w="100%">
            <Text
              fontSize={["45px", "60px", "70px", "50px"]}
              fontFamily="Red Hat Text, sans-serif"
              transform="scaleY(.9)"
              lineHeight={1.3}
              fontWeight="900"
            >
              My name is Adrian. <br />I am a Software Engineer <br /> based in
              London, UK.
            </Text>
          </Box>
          <Box w={["100%", "100%", "50%"]}>
            <Text>
              I am a Tech enthusiast. I curate vision with simple code.
            </Text>
          </Box>
        </Box>
      </Flex>
    </Box>
  );
}
