import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Flex, Box, Text, useColorModeValue } from "@chakra-ui/react";

import Navbar from "../Components/Layout/Navbar";
import Career from "../Components/Sections/career";

export default function Home() {
  const bgColor = useColorModeValue("gray.50", "blackAlpha.800");

  return (
    <Box>
      <Head>
        <title>Adrian Pantea Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      
      <Flex
        w="100vw"
        h={["100vh"]}
        px={[0, 0, 10, 40]}
        bg={bgColor}
        // border="1px solid red"
      >
        <Box
          w="100%"
          display="flex"
          flexDir="column"
          justifyContent="space-evenly"
          alignItems="flex-end"
          px={[5, 5, 0]}
        >
          <Box w="100%">
            <Text
              fontSize={["45px", "60px", "70px", "60px"]}
              fontFamily="Red Hat Text, sans-serif"
              transform="scaleY(.9)"
              lineHeight={1.3}
              fontWeight="900"
            >
              My name is Adrian. <br />I am a Software Engineer <br /> based in
              London, UK.
            </Text>
          </Box>
          <Box
            w={["100%", "100%", "50%"]}
            textAlign="end"
            fontWeight="500"
            // border="1px solid"
          >
            <Text>
              I am a Tech enthusiast. I curate vision with simple code.
            </Text>
          </Box>
        </Box>
      </Flex>
      
      <Career/>
    </Box>
  );
}
