import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Flex, Box, Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Adrian Pantea Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        w="100vw"
        h="100vh"
        border="1px solid red"
        maxW="100vw"
        // bg="#0B0A0A"
        // bg="#111"
        px={[0, 0, 10, 40]}
      >
        <Box border="1px solid" w="100%">
          <Heading>Index page</Heading>
        </Box>
      </Flex>
    </div>
  );
}
